import plugin from "tailwindcss/plugin";

/**
 * A Tailwind CSS plugin that generates colour themes using CSS variables
 *
 * @param options An object containing at least one theme object.
 * @returns A Tailwind CSS plugin with light, dark and colour filter themes
 */
export const coloursPlugin = plugin(
  ({ addBase, addUtilities }) => {
    // addBase({
    //   ":root,:root:where([data-theme='light'])": {
    //     "--neutral-1": "240, 22%, 99%",
    //     "--neutral-2": "240, 20%, 98%",
    //     "--neutral-3": "239, 13.4%, 95.4%",
    //     "--neutral-4": "238, 11.8%, 92.9%",
    //     "--neutral-5": "237, 11.1%, 90.5%",
    //     "--neutral-6": "236, 10.6%, 87.9%",
    //     "--neutral-7": "234, 10.4%, 84.4%",
    //     "--neutral-8": "231, 10.2%, 75.1%",
    //     "--neutral-9": "230, 6%, 57%",
    //     "--neutral-10": "227, 5.2%, 51.8%",
    //     "--neutral-11": "220, 6%, 40%",
    //     "--neutral-12": "210, 12%, 12.5%",
    //     "--accent-1": "225, 60%, 99.4%",
    //     "--accent-2": "223, 100%, 98.6%",
    //     "--accent-3": "223, 98.4%, 97.1%",
    //     "--accent-4": "223, 92.9%, 95%",
    //     "--accent-5": "224, 87.1%, 92%",
    //     "--accent-6": "224, 81.9%, 87.8%",
    //     "--accent-7": "225, 77.4%, 82.1%",
    //     "--accent-8": "226, 75.4%, 74.5%",
    //     "--accent-9": "226, 70%, 55.5%",
    //     "--accent-10": "226, 58.6%, 51.3%",
    //     "--accent-11": "226, 55%, 45%",
    //     "--accent-12": "226, 50%, 24%",
    //     "--success-1": "136, 50%, 98.9%",
    //     "--success-2": "138, 62.5%, 96.9%",
    //     "--success-3": "139, 55.2%, 94.5%",
    //     "--success-4": "140, 48.7%, 91%",
    //     "--success-5": "141, 43.7%, 86%",
    //     "--success-6": "143, 40.3%, 79%",
    //     "--success-7": "146, 38.5%, 69%",
    //     "--success-8": "151, 40.2%, 54.1%",
    //     "--success-9": "151, 55%, 41.5%",
    //     "--success-10": "152, 57.5%, 37.6%",
    //     "--success-11": "153, 67%, 28.5%",
    //     "--success-12": "155, 40%, 16.5%",
    //     "--danger-1": "359, 100%, 99.4%",
    //     "--danger-2": "0, 100%, 98.4%",
    //     "--danger-3": "360, 100%, 96.8%",
    //     "--danger-4": "360, 97.9%, 94.8%",
    //     "--danger-5": "360, 90.2%, 91.9%",
    //     "--danger-6": "360, 81.7%, 87.8%",
    //     "--danger-7": "359, 74.2%, 81.7%",
    //     "--danger-8": "359, 69.5%, 74.3%",
    //     "--danger-9": "358, 75%, 59%",
    //     "--danger-10": "358, 67.4%, 54.6%",
    //     "--danger-11": "358, 65%, 47%",
    //     "--danger-12": "350, 63%, 24%",
    //     "--attention-1": "39, 70%, 99%",
    //     "--attention-2": "40, 100%, 96.5%",
    //     "--attention-3": "45, 100%, 90.8%",
    //     "--attention-4": "44, 100%, 85.8%",
    //     "--attention-5": "40, 100%, 81.5%",
    //     "--attention-6": "39, 83.6%, 75.4%",
    //     "--attention-7": "37, 66.9%, 68.2%",
    //     "--attention-8": "35, 59.8%, 60%",
    //     "--attention-9": "42, 100%, 62%",
    //     "--attention-10": "42, 100%, 55%",
    //     "--attention-11": "25, 50%, 38%",
    //     "--attention-12": "25, 40%, 22%",
    //     "--overlay": "0, 0%, 0%, 0.608",
    //     "--text-neutral-default": "var(--neutral-12)",
    //     "--text-neutral-muted": "var(--neutral-11)",
    //     "--text-accent-default": "var(--accent-12)",
    //     "--text-accent-muted": "var(--accent-11)",
    //     "--text-success-default": "var(--success-12)",
    //     "--text-success-muted": "var(--success-11)",
    //     "--text-attention-default": "var(--attention-12)",
    //     "--text-attention-muted": "var(--attention-11)",
    //     "--text-danger-default": "var(--danger-12)",
    //     "--text-danger-muted": "var(--danger-11)",
    //     "--background-neutral-default": "var(--neutral-1)",
    //     "--background-neutral-muted": "var(--neutral-2)",
    //     "--background-accent-default": "var(--accent-1)",
    //     "--background-accent-muted": "var(--accent-2)",
    //     "--background-success-default": "var(--success-1)",
    //     "--background-success-muted": "var(--success-2)",
    //     "--background-attention-default": "var(--attention-1)",
    //     "--background-attention-muted": "var(--attention-2)",
    //     "--background-danger-default": "var(--danger-1)",
    //     "--background-danger-muted": "var(--danger-2)",
    //     "--border-neutral-muted": "var(--neutral-6)",
    //     "--border-neutral-default": "var(--neutral-7)",
    //     "--border-neutral-dark": "var(--neutral-8)",
    //     "--border-accent-muted": "var(--accent-6)",
    //     "--border-accent-default": "var(--accent-7)",
    //     "--border-accent-dark": "var(--accent-8)",
    //     "--border-success-muted": "var(--success-6)",
    //     "--border-success-default": "var(--success-7)",
    //     "--border-success-dark": "var(--success-8)",
    //     "--border-attention-muted": "var(--attention-6)",
    //     "--border-attention-default": "var(--attention-7)",
    //     "--border-attention-dark": "var(--attention-8)",
    //     "--border-danger-muted": "var(--danger-6)",
    //     "--border-danger-default": "var(--danger-7)",
    //     "--border-danger-dark": "var(--danger-8)",
    //     "--ring-neutral": "var(--neutral-7)",
    //     "--ring-accent": "var(--accent-7)",
    //     "--ring-success": "var(--success-7)",
    //     "--ring-attention": "var(--attention-7)",
    //     "--ring-danger": "var(--danger-7)",
    //     "--separator-neutral": "var(--neutral-6)",
    //     "--separator-accent": "var(--accent-6)",
    //     "--separator-success": "var(--success-6)",
    //     "--separator-attention": "var(--attention-6)",
    //     "--separator-danger": "var(--danger-6)",
    //     "--component-background-neutral-default": "var(--neutral-3)",
    //     "--component-background-neutral-hover": "var(--neutral-4)",
    //     "--component-background-neutral-pressed": "var(--neutral-5)",
    //     "--component-background-neutral-dark": "var(--neutral-6)",
    //     "--component-background-neutral-solid-default": "var(--neutral-9)",
    //     "--component-background-neutral-solid-hover": "var(--neutral-10)",
    //     "--component-background-accent-default": "var(--accent-3)",
    //     "--component-background-accent-hover": "var(--accent-4)",
    //     "--component-background-accent-pressed": "var(--accent-5)",
    //     "--component-background-accent-dark": "var(--accent-6)",
    //     "--component-background-accent-solid-default": "var(--accent-9)",
    //     "--component-background-accent-solid-hover": "var(--accent-10)",
    //     "--component-background-success-default": "var(--success-3)",
    //     "--component-background-success-hover": "var(--success-4)",
    //     "--component-background-success-pressed": "var(--success-5)",
    //     "--component-background-success-dark": "var(--success-6)",
    //     "--component-background-success-solid-default": "var(--success-9)",
    //     "--component-background-success-solid-hover": "var(--success-10)",
    //     "--component-background-attention-default": "var(--attention-3)",
    //     "--component-background-attention-hover": "var(--attention-4)",
    //     "--component-background-attention-pressed": "var(--attention-5)",
    //     "--component-background-attention-dark": "var(--attention-6)",
    //     "--component-background-attention-solid-default": "var(--attention-9)",
    //     "--component-background-attention-solid-hover": "var(--attention-10)",
    //     "--component-background-danger-default": "var(--danger-3)",
    //     "--component-background-danger-hover": "var(--danger-4)",
    //     "--component-background-danger-pressed": "var(--danger-5)",
    //     "--component-background-danger-dark": "var(--danger-6)",
    //     "--component-background-danger-solid-default": "var(--danger-9)",
    //     "--component-background-danger-solid-hover": "var(--danger-10)"
    //   },
    //   '[data-theme="dark"]': {
    //     "--neutral-1": "240, 5%, 9.8%",
    //     "--neutral-2": "240, 6.9%, 11.4%",
    //     "--neutral-3": "227, 6.7%, 16.4%",
    //     "--neutral-4": "222, 6.6%, 19.4%",
    //     "--neutral-5": "218, 6.5%, 22.1%",
    //     "--neutral-6": "214, 6.4%, 25.1%",
    //     "--neutral-7": "209, 6.2%, 29.4%",
    //     "--neutral-8": "202, 5.8%, 37.5%",
    //     "--neutral-9": "220, 6%, 44%",
    //     "--neutral-10": "218, 5.3%, 51.5%",
    //     "--neutral-11": "220, 7%, 70%",
    //     "--neutral-12": "220, 7%, 93.5%",
    //     "--accent-1": "229, 24%, 10%",
    //     "--accent-2": "230, 36.4%, 12.9%",
    //     "--accent-3": "228, 42.7%, 18.1%",
    //     "--accent-4": "227, 45.6%, 21.4%",
    //     "--accent-5": "227, 47.8%, 24.4%",
    //     "--accent-6": "226, 50.3%, 28.8%",
    //     "--accent-7": "226, 53.3%, 36.6%",
    //     "--accent-8": "226, 60%, 52%",
    //     "--accent-9": "226, 70%, 55.5%",
    //     "--accent-10": "230, 73.9%, 63.3%",
    //     "--accent-11": "235, 100%, 80%",
    //     "--accent-12": "235, 93%, 93%",
    //     "--success-1": "146, 30%, 7.4%",
    //     "--success-2": "154, 31.8%, 8.6%",
    //     "--success-3": "154, 37.6%, 11.5%",
    //     "--success-4": "154, 41%, 13.6%",
    //     "--success-5": "154, 43.7%, 15.7%",
    //     "--success-6": "154, 46.7%, 18.7%",
    //     "--success-7": "153, 50.3%, 24.4%",
    //     "--success-8": "151, 52.2%, 36.1%",
    //     "--success-9": "151, 55%, 41.5%",
    //     "--success-10": "151, 55.2%, 46.7%",
    //     "--success-11": "151, 65%, 54%",
    //     "--success-12": "144, 70%, 82%",
    //     "--danger-1": "353, 23%, 9.8%",
    //     "--danger-2": "354, 30.2%, 12.4%",
    //     "--danger-3": "353, 40.8%, 16.4%",
    //     "--danger-4": "353, 46.3%, 19.2%",
    //     "--danger-5": "353, 51.2%, 22.1%",
    //     "--danger-6": "353, 57.3%, 26.2%",
    //     "--danger-7": "354, 65.7%, 33.2%",
    //     "--danger-8": "358, 75%, 47.1%",
    //     "--danger-9": "358, 75%, 59%",
    //     "--danger-10": "359, 84.8%, 67.6%",
    //     "--danger-11": "358, 100%, 76%",
    //     "--danger-12": "350, 100%, 91%",
    //     "--attention-1": "36, 100%, 6.1%",
    //     "--attention-2": "36, 80.5%, 8%",
    //     "--attention-3": "35, 63.4%, 11.4%",
    //     "--attention-4": "34, 58.8%, 14.1%",
    //     "--attention-5": "34, 58.1%, 16.7%",
    //     "--attention-6": "35, 58.3%, 20.5%",
    //     "--attention-7": "35, 59%, 27.4%",
    //     "--attention-8": "36, 60.2%, 41.4%",
    //     "--attention-9": "42, 100%, 62%",
    //     "--attention-10": "43, 100%, 64%",
    //     "--attention-11": "43, 100%, 65%",
    //     "--attention-12": "41, 100%, 85%",
    //     "--overlay": "0, 0%, 0%, 0.608",
    //     "--text-neutral-default": "var(--neutral-12)",
    //     "--text-neutral-muted": "var(--neutral-11)",
    //     "--text-accent-default": "var(--accent-12)",
    //     "--text-accent-muted": "var(--accent-11)",
    //     "--text-success-default": "var(--success-12)",
    //     "--text-success-muted": "var(--success-11)",
    //     "--text-attention-default": "var(--attention-12)",
    //     "--text-attention-muted": "var(--attention-11)",
    //     "--text-danger-default": "var(--danger-12)",
    //     "--text-danger-muted": "var(--danger-11)",
    //     "--background-neutral-default": "var(--neutral-1)",
    //     "--background-neutral-muted": "var(--neutral-2)",
    //     "--background-accent-default": "var(--accent-1)",
    //     "--background-accent-muted": "var(--accent-2)",
    //     "--background-success-default": "var(--success-1)",
    //     "--background-success-muted": "var(--success-2)",
    //     "--background-attention-default": "var(--attention-1)",
    //     "--background-attention-muted": "var(--attention-2)",
    //     "--background-danger-default": "var(--danger-1)",
    //     "--background-danger-muted": "var(--danger-2)",
    //     "--border-neutral-muted": "var(--neutral-6)",
    //     "--border-neutral-default": "var(--neutral-7)",
    //     "--border-neutral-dark": "var(--neutral-8)",
    //     "--border-accent-muted": "var(--accent-6)",
    //     "--border-accent-default": "var(--accent-7)",
    //     "--border-accent-dark": "var(--accent-8)",
    //     "--border-success-muted": "var(--success-6)",
    //     "--border-success-default": "var(--success-7)",
    //     "--border-success-dark": "var(--success-8)",
    //     "--border-attention-muted": "var(--attention-6)",
    //     "--border-attention-default": "var(--attention-7)",
    //     "--border-attention-dark": "var(--attention-8)",
    //     "--border-danger-muted": "var(--danger-6)",
    //     "--border-danger-default": "var(--danger-7)",
    //     "--border-danger-dark": "var(--danger-8)",
    //     "--ring-neutral": "var(--neutral-7)",
    //     "--ring-accent": "var(--accent-7)",
    //     "--ring-success": "var(--success-7)",
    //     "--ring-attention": "var(--attention-7)",
    //     "--ring-danger": "var(--danger-7)",
    //     "--separator-neutral": "var(--neutral-6)",
    //     "--separator-accent": "var(--accent-6)",
    //     "--separator-success": "var(--success-6)",
    //     "--separator-attention": "var(--attention-6)",
    //     "--separator-danger": "var(--danger-6)",
    //     "--component-background-neutral-default": "var(--neutral-3)",
    //     "--component-background-neutral-hover": "var(--neutral-4)",
    //     "--component-background-neutral-pressed": "var(--neutral-5)",
    //     "--component-background-neutral-dark": "var(--neutral-6)",
    //     "--component-background-neutral-solid-default": "var(--neutral-9)",
    //     "--component-background-neutral-solid-hover": "var(--neutral-10)",
    //     "--component-background-accent-default": "var(--accent-3)",
    //     "--component-background-accent-hover": "var(--accent-4)",
    //     "--component-background-accent-pressed": "var(--accent-5)",
    //     "--component-background-accent-dark": "var(--accent-6)",
    //     "--component-background-accent-solid-default": "var(--accent-9)",
    //     "--component-background-accent-solid-hover": "var(--accent-10)",
    //     "--component-background-success-default": "var(--success-3)",
    //     "--component-background-success-hover": "var(--success-4)",
    //     "--component-background-success-pressed": "var(--success-5)",
    //     "--component-background-success-dark": "var(--success-6)",
    //     "--component-background-success-solid-default": "var(--success-9)",
    //     "--component-background-success-solid-hover": "var(--success-10)",
    //     "--component-background-attention-default": "var(--attention-3)",
    //     "--component-background-attention-hover": "var(--attention-4)",
    //     "--component-background-attention-pressed": "var(--attention-5)",
    //     "--component-background-attention-dark": "var(--attention-6)",
    //     "--component-background-attention-solid-default": "var(--attention-9)",
    //     "--component-background-attention-solid-hover": "var(--attention-10)",
    //     "--component-background-danger-default": "var(--danger-3)",
    //     "--component-background-danger-hover": "var(--danger-4)",
    //     "--component-background-danger-pressed": "var(--danger-5)",
    //     "--component-background-danger-dark": "var(--danger-6)",
    //     "--component-background-danger-solid-default": "var(--danger-9)",
    //     "--component-background-danger-solid-hover": "var(--danger-10)"
    //   },
    //   '[data-filter="deuteranopia"]:where([data-theme="light"])': {
    //     "--success-1": "210, 100%, 99%",
    //     "--success-2": "207, 100%, 98%",
    //     "--success-3": "205, 92%, 95%",
    //     "--success-4": "203, 100%, 92%",
    //     "--success-5": "206, 100%, 88%",
    //     "--success-6": "207, 93%, 83%",
    //     "--success-7": "207, 85%, 76%",
    //     "--success-8": "206, 82%, 65%",
    //     "--success-9": "206, 100%, 50%",
    //     "--success-10": "207, 96%, 48%",
    //     "--success-11": "208, 88%, 43%",
    //     "--success-12": "216, 71%, 23%",
    //     "--danger-1": "30, 50%, 99%",
    //     "--danger-2": "30, 50%, 98%",
    //     "--danger-3": "28, 45%, 94%",
    //     "--danger-4": "29, 43%, 90%",
    //     "--danger-5": "29, 45%, 86%",
    //     "--danger-6": "29, 45%, 81%",
    //     "--danger-7": "29, 47%, 74%",
    //     "--danger-8": "28, 45%, 65%",
    //     "--danger-9": "28, 34%, 51%",
    //     "--danger-10": "26, 32%, 48%",
    //     "--danger-11": "24, 30%, 39%",
    //     "--danger-12": "19, 15%, 21%",
    //     "--text-success-default": "var(--success-12)",
    //     "--text-success-muted": "var(--success-11)",
    //     "--text-danger-default": "var(--danger-12)",
    //     "--text-danger-muted": "var(--danger-11)",
    //     "--background-success-default": "var(--success-1)",
    //     "--background-success-muted": "var(--success-2)",
    //     "--background-danger-default": "var(--danger-1)",
    //     "--background-danger-muted": "var(--danger-2)",
    //     "--border-success-muted": "var(--success-6)",
    //     "--border-success-default": "var(--success-7)",
    //     "--border-success-dark": "var(--success-8)",
    //     "--border-danger-muted": "var(--danger-6)",
    //     "--border-danger-default": "var(--danger-7)",
    //     "--border-danger-dark": "var(--danger-8)",
    //     "--ring-success": "var(--success-7)",
    //     "--ring-danger": "var(--danger-7)",
    //     "--separator-success": "var(--success-6)",
    //     "--separator-danger": "var(--danger-6)",
    //     "--component-background-success-default": "var(--success-3)",
    //     "--component-background-success-hover": "var(--success-4)",
    //     "--component-background-success-pressed": "var(--success-5)",
    //     "--component-background-success-dark": "var(--success-6)",
    //     "--component-background-success-solid-default": "var(--success-9)",
    //     "--component-background-success-solid-hover": "var(--success-10)",
    //     "--component-background-danger-default": "var(--danger-3)",
    //     "--component-background-danger-hover": "var(--danger-4)",
    //     "--component-background-danger-pressed": "var(--danger-5)",
    //     "--component-background-danger-dark": "var(--danger-6)",
    //     "--component-background-danger-solid-default": "var(--danger-9)",
    //     "--component-background-danger-solid-hover": "var(--danger-10)"
    //   },
    //   '[data-filter="deuteranopia"]:where([data-theme="dark"])': {
    //     "--success-1": "215, 42%, 9%",
    //     "--success-2": "218, 39%, 11%",
    //     "--success-3": "212, 69%, 16%",
    //     "--success-4": "209, 100%, 19%",
    //     "--success-5": "207, 100%, 23%",
    //     "--success-6": "209, 79%, 30%",
    //     "--success-7": "211, 66%, 37%",
    //     "--success-8": "211, 65%, 45%",
    //     "--success-9": "206, 100%, 50%",
    //     "--success-10": "210, 100%, 62%",
    //     "--success-11": "210, 100%, 72%",
    //     "--success-12": "205, 100%, 88%",
    //     "--danger-1": "40, 9%, 6%",
    //     "--danger-2": "20, 12%, 10%",
    //     "--danger-3": "22, 16%, 14%",
    //     "--danger-4": "26, 19%, 16%",
    //     "--danger-5": "25, 22%, 20%",
    //     "--danger-6": "26, 24%, 24%",
    //     "--danger-7": "26, 26%, 30%",
    //     "--danger-8": "28, 28%, 38%",
    //     "--danger-9": "28, 34%, 51%",
    //     "--danger-10": "27, 36%, 56%",
    //     "--danger-11": "28, 50%, 72%",
    //     "--danger-12": "35, 61%, 87%",
    //     "--text-success-default": "var(--success-12)",
    //     "--text-success-muted": "var(--success-11)",
    //     "--text-danger-default": "var(--danger-12)",
    //     "--text-danger-muted": "var(--danger-11)",
    //     "--background-success-default": "var(--success-1)",
    //     "--background-success-muted": "var(--success-2)",
    //     "--background-danger-default": "var(--danger-1)",
    //     "--background-danger-muted": "var(--danger-2)",
    //     "--border-success-muted": "var(--success-6)",
    //     "--border-success-default": "var(--success-7)",
    //     "--border-success-dark": "var(--success-8)",
    //     "--border-danger-muted": "var(--danger-6)",
    //     "--border-danger-default": "var(--danger-7)",
    //     "--border-danger-dark": "var(--danger-8)",
    //     "--ring-success": "var(--success-7)",
    //     "--ring-danger": "var(--danger-7)",
    //     "--separator-success": "var(--success-6)",
    //     "--separator-danger": "var(--danger-6)",
    //     "--component-background-success-default": "var(--success-3)",
    //     "--component-background-success-hover": "var(--success-4)",
    //     "--component-background-success-pressed": "var(--success-5)",
    //     "--component-background-success-dark": "var(--success-6)",
    //     "--component-background-success-solid-default": "var(--success-9)",
    //     "--component-background-success-solid-hover": "var(--success-10)",
    //     "--component-background-danger-default": "var(--danger-3)",
    //     "--component-background-danger-hover": "var(--danger-4)",
    //     "--component-background-danger-pressed": "var(--danger-5)",
    //     "--component-background-danger-dark": "var(--danger-6)",
    //     "--component-background-danger-solid-default": "var(--danger-9)",
    //     "--component-background-danger-solid-hover": "var(--danger-10)"
    //   },
    //   '[data-filter="protanopia"]:where([data-theme="light"])': {
    //     "--success-1": "210, 100%, 99%",
    //     "--success-2": "207, 100%, 98%",
    //     "--success-3": "205, 92%, 95%",
    //     "--success-4": "203, 100%, 92%",
    //     "--success-5": "206, 100%, 88%",
    //     "--success-6": "207, 93%, 83%",
    //     "--success-7": "207, 85%, 76%",
    //     "--success-8": "206, 82%, 65%",
    //     "--success-9": "206, 100%, 50%",
    //     "--success-10": "207, 96%, 48%",
    //     "--success-11": "208, 88%, 43%",
    //     "--success-12": "216, 71%, 23%",
    //     "--danger-1": "30, 50%, 99%",
    //     "--danger-2": "30, 50%, 98%",
    //     "--danger-3": "28, 45%, 94%",
    //     "--danger-4": "29, 43%, 90%",
    //     "--danger-5": "29, 45%, 86%",
    //     "--danger-6": "29, 45%, 81%",
    //     "--danger-7": "29, 47%, 74%",
    //     "--danger-8": "28, 45%, 65%",
    //     "--danger-9": "28, 34%, 51%",
    //     "--danger-10": "26, 32%, 48%",
    //     "--danger-11": "24, 30%, 39%",
    //     "--danger-12": "19, 15%, 21%",
    //     "--text-success-default": "var(--success-12)",
    //     "--text-success-muted": "var(--success-11)",
    //     "--text-danger-default": "var(--danger-12)",
    //     "--text-danger-muted": "var(--danger-11)",
    //     "--background-success-default": "var(--success-1)",
    //     "--background-success-muted": "var(--success-2)",
    //     "--background-danger-default": "var(--danger-1)",
    //     "--background-danger-muted": "var(--danger-2)",
    //     "--border-success-muted": "var(--success-6)",
    //     "--border-success-default": "var(--success-7)",
    //     "--border-success-dark": "var(--success-8)",
    //     "--border-danger-muted": "var(--danger-6)",
    //     "--border-danger-default": "var(--danger-7)",
    //     "--border-danger-dark": "var(--danger-8)",
    //     "--ring-success": "var(--success-7)",
    //     "--ring-danger": "var(--danger-7)",
    //     "--separator-success": "var(--success-6)",
    //     "--separator-danger": "var(--danger-6)",
    //     "--component-background-success-default": "var(--success-3)",
    //     "--component-background-success-hover": "var(--success-4)",
    //     "--component-background-success-pressed": "var(--success-5)",
    //     "--component-background-success-dark": "var(--success-6)",
    //     "--component-background-success-solid-default": "var(--success-9)",
    //     "--component-background-success-solid-hover": "var(--success-10)",
    //     "--component-background-danger-default": "var(--danger-3)",
    //     "--component-background-danger-hover": "var(--danger-4)",
    //     "--component-background-danger-pressed": "var(--danger-5)",
    //     "--component-background-danger-dark": "var(--danger-6)",
    //     "--component-background-danger-solid-default": "var(--danger-9)",
    //     "--component-background-danger-solid-hover": "var(--danger-10)"
    //   },
    //   '[data-filter="protanopia"]:where([data-theme="dark"])': {
    //     "--success-1": "215, 42%, 9%",
    //     "--success-2": "218, 39%, 11%",
    //     "--success-3": "212, 69%, 16%",
    //     "--success-4": "209, 100%, 19%",
    //     "--success-5": "207, 100%, 23%",
    //     "--success-6": "209, 79%, 30%",
    //     "--success-7": "211, 66%, 37%",
    //     "--success-8": "211, 65%, 45%",
    //     "--success-9": "206, 100%, 50%",
    //     "--success-10": "210, 100%, 62%",
    //     "--success-11": "210, 100%, 72%",
    //     "--success-12": "205, 100%, 88%",
    //     "--danger-1": "40, 9%, 6%",
    //     "--danger-2": "20, 12%, 10%",
    //     "--danger-3": "22, 16%, 14%",
    //     "--danger-4": "26, 19%, 16%",
    //     "--danger-5": "25, 22%, 20%",
    //     "--danger-6": "26, 24%, 24%",
    //     "--danger-7": "26, 26%, 30%",
    //     "--danger-8": "28, 28%, 38%",
    //     "--danger-9": "28, 34%, 51%",
    //     "--danger-10": "27, 36%, 56%",
    //     "--danger-11": "28, 50%, 72%",
    //     "--danger-12": "35, 61%, 87%",
    //     "--text-success-default": "var(--success-12)",
    //     "--text-success-muted": "var(--success-11)",
    //     "--text-danger-default": "var(--danger-12)",
    //     "--text-danger-muted": "var(--danger-11)",
    //     "--background-success-default": "var(--success-1)",
    //     "--background-success-muted": "var(--success-2)",
    //     "--background-danger-default": "var(--danger-1)",
    //     "--background-danger-muted": "var(--danger-2)",
    //     "--border-success-muted": "var(--success-6)",
    //     "--border-success-default": "var(--success-7)",
    //     "--border-success-dark": "var(--success-8)",
    //     "--border-danger-muted": "var(--danger-6)",
    //     "--border-danger-default": "var(--danger-7)",
    //     "--border-danger-dark": "var(--danger-8)",
    //     "--ring-success": "var(--success-7)",
    //     "--ring-danger": "var(--danger-7)",
    //     "--separator-success": "var(--success-6)",
    //     "--separator-danger": "var(--danger-6)",
    //     "--component-background-success-default": "var(--success-3)",
    //     "--component-background-success-hover": "var(--success-4)",
    //     "--component-background-success-pressed": "var(--success-5)",
    //     "--component-background-success-dark": "var(--success-6)",
    //     "--component-background-success-solid-default": "var(--success-9)",
    //     "--component-background-success-solid-hover": "var(--success-10)",
    //     "--component-background-danger-default": "var(--danger-3)",
    //     "--component-background-danger-hover": "var(--danger-4)",
    //     "--component-background-danger-pressed": "var(--danger-5)",
    //     "--component-background-danger-dark": "var(--danger-6)",
    //     "--component-background-danger-solid-default": "var(--danger-9)",
    //     "--component-background-danger-solid-hover": "var(--danger-10)"
    //   },
    //   '[data-filter="tritanopia"]:where([data-theme="light"])': {
    //     "--danger-1": "0, 100%, 99%",
    //     "--danger-2": "7, 100%, 98%",
    //     "--danger-3": "10, 92%, 95%",
    //     "--danger-4": "12, 100%, 91%",
    //     "--danger-5": "11, 100%, 88%",
    //     "--danger-6": "11, 95%, 84%",
    //     "--danger-7": "10, 82%, 78%",
    //     "--danger-8": "10, 75%, 70%",
    //     "--danger-9": "10, 78%, 54%",
    //     "--danger-10": "10, 73%, 51%",
    //     "--danger-11": "10, 82%, 45%",
    //     "--danger-12": "8, 50%, 24%",
    //     "--success-1": "120, 60%, 99%",
    //     "--success-2": "120, 43%, 97%",
    //     "--success-3": "120, 42%, 94%",
    //     "--success-4": "123, 45%, 90%",
    //     "--success-5": "122, 40%, 85%",
    //     "--success-6": "124, 39%, 78%",
    //     "--success-7": "126, 37%, 69%",
    //     "--success-8": "131, 38%, 56%",
    //     "--success-9": "131, 41%, 46%",
    //     "--success-10": "131, 43%, 43%",
    //     "--success-11": "132, 50%, 33%",
    //     "--success-12": "131, 30%, 18%",
    //     "--accent-1": "160, 60%, 99%",
    //     "--accent-2": "146, 47%, 97%",
    //     "--accent-3": "145, 52%, 94%",
    //     "--accent-4": "149, 49%, 89%",
    //     "--accent-5": "152, 46%, 84%",
    //     "--accent-6": "154, 43%, 77%",
    //     "--accent-7": "159, 41%, 68%",
    //     "--accent-8": "164, 42%, 53%",
    //     "--accent-9": "164, 60%, 40%",
    //     "--accent-10": "164, 60%, 37%",
    //     "--accent-11": "164, 61%, 32%",
    //     "--accent-12": "160, 34%, 17%",
    //     "--text-accent-default": "var(--accent-12)",
    //     "--text-accent-muted": "var(--accent-11)",
    //     "--text-success-default": "var(--success-12)",
    //     "--text-success-muted": "var(--success-11)",
    //     "--text-danger-default": "var(--danger-12)",
    //     "--text-danger-muted": "var(--danger-11)",
    //     "--background-accent-default": "var(--accent-1)",
    //     "--background-accent-muted": "var(--accent-2)",
    //     "--background-success-default": "var(--success-1)",
    //     "--background-success-muted": "var(--success-2)",
    //     "--background-danger-default": "var(--danger-1)",
    //     "--background-danger-muted": "var(--danger-2)",
    //     "--border-accent-muted": "var(--accent-6)",
    //     "--border-accent-default": "var(--accent-7)",
    //     "--border-accent-dark": "var(--accent-8)",
    //     "--border-success-muted": "var(--success-6)",
    //     "--border-success-default": "var(--success-7)",
    //     "--border-success-dark": "var(--success-8)",
    //     "--border-danger-muted": "var(--danger-6)",
    //     "--border-danger-default": "var(--danger-7)",
    //     "--border-danger-dark": "var(--danger-8)",
    //     "--ring-accent": "var(--accent-7)",
    //     "--ring-success": "var(--success-7)",
    //     "--ring-danger": "var(--danger-7)",
    //     "--separator-accent": "var(--accent-6)",
    //     "--separator-success": "var(--success-6)",
    //     "--separator-danger": "var(--danger-6)",
    //     "--component-background-accent-default": "var(--accent-3)",
    //     "--component-background-accent-hover": "var(--accent-4)",
    //     "--component-background-accent-pressed": "var(--accent-5)",
    //     "--component-background-accent-dark": "var(--accent-6)",
    //     "--component-background-accent-solid-default": "var(--accent-9)",
    //     "--component-background-accent-solid-hover": "var(--accent-10)",
    //     "--component-background-success-default": "var(--success-3)",
    //     "--component-background-success-hover": "var(--success-4)",
    //     "--component-background-success-pressed": "var(--success-5)",
    //     "--component-background-success-dark": "var(--success-6)",
    //     "--component-background-success-solid-default": "var(--success-9)",
    //     "--component-background-success-solid-hover": "var(--success-10)",
    //     "--component-background-danger-default": "var(--danger-3)",
    //     "--component-background-danger-hover": "var(--danger-4)",
    //     "--component-background-danger-pressed": "var(--danger-5)",
    //     "--component-background-danger-dark": "var(--danger-6)",
    //     "--component-background-danger-solid-default": "var(--danger-9)",
    //     "--component-background-danger-solid-hover": "var(--danger-10)"
    //   },
    //   '[data-filter="tritanopia"]:where([data-theme="dark"])': {
    //     "--accent-1": "158, 24%, 7%",
    //     "--accent-2": "156, 22%, 9%",
    //     "--accent-3": "157, 51%, 12%",
    //     "--accent-4": "161, 69%, 14%",
    //     "--accent-5": "161, 62%, 17%",
    //     "--accent-6": "162, 53%, 22%",
    //     "--accent-7": "162, 49%, 27%",
    //     "--accent-8": "164, 50%, 33%",
    //     "--accent-9": "164, 60%, 40%",
    //     "--accent-10": "164, 64%, 42%",
    //     "--accent-11": "163, 75%, 48%",
    //     "--accent-12": "155, 69%, 81%",
    //     "--success-1": "146, 20%, 7%",
    //     "--success-2": "130, 13%, 9%",
    //     "--success-3": "132, 22%, 14%",
    //     "--success-4": "134, 33%, 17%",
    //     "--success-5": "134, 32%, 21%",
    //     "--success-6": "133, 32%, 26%",
    //     "--success-7": "132, 31%, 31%",
    //     "--success-8": "131, 32%, 36%",
    //     "--success-9": "131, 41%, 46%",
    //     "--success-10": "131, 39%, 51%",
    //     "--success-11": "131, 50%, 63%",
    //     "--success-12": "120, 61%, 85%",
    //     "--danger-1": "0, 17%, 8%",
    //     "--danger-2": "10, 24%, 10%",
    //     "--danger-3": "5, 48%, 15%",
    //     "--danger-4": "4, 64%, 19%",
    //     "--danger-5": "5, 62%, 23%",
    //     "--danger-6": "7, 55%, 28%",
    //     "--danger-7": "9, 49%, 35%",
    //     "--danger-8": "10, 50%, 45%",
    //     "--danger-9": "10, 78%, 54%",
    //     "--danger-10": "11, 82%, 59%",
    //     "--danger-11": "12, 100%, 75%",
    //     "--danger-12": "10, 86%, 89%",
    //     "--text-accent-default": "var(--accent-12)",
    //     "--text-accent-muted": "var(--accent-11)",
    //     "--text-success-default": "var(--success-12)",
    //     "--text-success-muted": "var(--success-11)",
    //     "--text-danger-default": "var(--danger-12)",
    //     "--text-danger-muted": "var(--danger-11)",
    //     "--background-accent-default": "var(--accent-1)",
    //     "--background-accent-muted": "var(--accent-2)",
    //     "--background-success-default": "var(--success-1)",
    //     "--background-success-muted": "var(--success-2)",
    //     "--background-danger-default": "var(--danger-1)",
    //     "--background-danger-muted": "var(--danger-2)",
    //     "--border-accent-muted": "var(--accent-6)",
    //     "--border-accent-default": "var(--accent-7)",
    //     "--border-accent-dark": "var(--accent-8)",
    //     "--border-success-muted": "var(--success-6)",
    //     "--border-success-default": "var(--success-7)",
    //     "--border-success-dark": "var(--success-8)",
    //     "--border-danger-muted": "var(--danger-6)",
    //     "--border-danger-default": "var(--danger-7)",
    //     "--border-danger-dark": "var(--danger-8)",
    //     "--ring-accent": "var(--accent-7)",
    //     "--ring-success": "var(--success-7)",
    //     "--ring-danger": "var(--danger-7)",
    //     "--separator-accent": "var(--accent-6)",
    //     "--separator-success": "var(--success-6)",
    //     "--separator-danger": "var(--danger-6)",
    //     "--component-background-accent-default": "var(--accent-3)",
    //     "--component-background-accent-hover": "var(--accent-4)",
    //     "--component-background-accent-pressed": "var(--accent-5)",
    //     "--component-background-accent-dark": "var(--accent-6)",
    //     "--component-background-accent-solid-default": "var(--accent-9)",
    //     "--component-background-accent-solid-hover": "var(--accent-10)",
    //     "--component-background-success-default": "var(--success-3)",
    //     "--component-background-success-hover": "var(--success-4)",
    //     "--component-background-success-pressed": "var(--success-5)",
    //     "--component-background-success-dark": "var(--success-6)",
    //     "--component-background-success-solid-default": "var(--success-9)",
    //     "--component-background-success-solid-hover": "var(--success-10)",
    //     "--component-background-danger-default": "var(--danger-3)",
    //     "--component-background-danger-hover": "var(--danger-4)",
    //     "--component-background-danger-pressed": "var(--danger-5)",
    //     "--component-background-danger-dark": "var(--danger-6)",
    //     "--component-background-danger-solid-default": "var(--danger-9)",
    //     "--component-background-danger-solid-hover": "var(--danger-10)"
    //   }
    // });

    addBase({
      ':root,:root:where([data-theme="light"])': {
        "--neutral-1": "#fcfcfd",
        "--neutral-2": "#f9f9fb",
        "--neutral-3": "#f0f0f3",
        "--neutral-4": "#e8e8ec",
        "--neutral-5": "#e0e1e6",
        "--neutral-6": "#d9d9e0",
        "--neutral-7": "#cdced6",
        "--neutral-8": "#b9bbc6",
        "--neutral-9": "#8b8d98",
        "--neutral-10": "#80838d",
        "--neutral-11": "#60646c",
        "--neutral-12": "#1c2024",
        "--accent-1": "#fdfdfe",
        "--accent-2": "#f7f9ff",
        "--accent-3": "#edf2fe",
        "--accent-4": "#e1e9ff",
        "--accent-5": "#d2deff",
        "--accent-6": "#c1d0ff",
        "--accent-7": "#abbdf9",
        "--accent-8": "#8da4ef",
        "--accent-9": "#3e63dd",
        "--accent-10": "#3358d4",
        "--accent-11": "#3a5bc7",
        "--accent-12": "#1f2d5c",
        "--success-1": "#fbfefc",
        "--success-2": "#f4fbf6",
        "--success-3": "#e6f6eb",
        "--success-4": "#d6f1df",
        "--success-5": "#c4e8d1",
        "--success-6": "#adddc0",
        "--success-7": "#8eceaa",
        "--success-8": "#5bb98b",
        "--success-9": "#30a46c",
        "--success-10": "#2b9a66",
        "--success-11": "#218358",
        "--success-12": "#193b2d",
        "--danger-1": "#fffcfc",
        "--danger-2": "#fff7f7",
        "--danger-3": "#feebec",
        "--danger-4": "#ffdbdc",
        "--danger-5": "#ffcdce",
        "--danger-6": "#fdbdbe",
        "--danger-7": "#f4a9aa",
        "--danger-8": "#eb8e90",
        "--danger-9": "#e5484d",
        "--danger-10": "#dc3e42",
        "--danger-11": "#ce2c31",
        "--danger-12": "#641723",
        "--attention-1": "#fefdfb",
        "--attention-2": "#fefbe9",
        "--attention-3": "#fff7c2",
        "--attention-4": "#ffee9c",
        "--attention-5": "#fbe577",
        "--attention-6": "#f3d673",
        "--attention-7": "#e9c162",
        "--attention-8": "#e2a336",
        "--attention-9": "#ffc53d",
        "--attention-10": "#ffba18",
        "--attention-11": "#ab6400",
        "--attention-12": "#4f3422",
        "--overlay": "#000000b3",
        "--text-neutral-default": "var(--neutral-12)",
        "--text-neutral-muted": "var(--neutral-11)",
        "--text-accent-default": "var(--accent-12)",
        "--text-accent-muted": "var(--accent-11)",
        "--text-success-default": "var(--success-12)",
        "--text-success-muted": "var(--success-11)",
        "--text-attention-default": "var(--attention-12)",
        "--text-attention-muted": "var(--attention-11)",
        "--text-danger-default": "var(--danger-12)",
        "--text-danger-muted": "var(--danger-11)",
        "--background-neutral-default": "var(--neutral-1)",
        "--background-neutral-muted": "var(--neutral-2)",
        "--background-accent-default": "var(--accent-1)",
        "--background-accent-muted": "var(--accent-2)",
        "--background-success-default": "var(--success-1)",
        "--background-success-muted": "var(--success-2)",
        "--background-attention-default": "var(--attention-1)",
        "--background-attention-muted": "var(--attention-2)",
        "--background-danger-default": "var(--danger-1)",
        "--background-danger-muted": "var(--danger-2)",
        "--border-neutral-muted": "var(--neutral-6)",
        "--border-neutral-default": "var(--neutral-7)",
        "--border-neutral-dark": "var(--neutral-8)",
        "--border-accent-muted": "var(--accent-6)",
        "--border-accent-default": "var(--accent-7)",
        "--border-accent-dark": "var(--accent-8)",
        "--border-success-muted": "var(--success-6)",
        "--border-success-default": "var(--success-7)",
        "--border-success-dark": "var(--success-8)",
        "--border-attention-muted": "var(--attention-6)",
        "--border-attention-default": "var(--attention-7)",
        "--border-attention-dark": "var(--attention-8)",
        "--border-danger-muted": "var(--danger-6)",
        "--border-danger-default": "var(--danger-7)",
        "--border-danger-dark": "var(--danger-8)",
        "--ring-neutral": "var(--neutral-7)",
        "--ring-accent": "var(--accent-7)",
        "--ring-success": "var(--success-7)",
        "--ring-attention": "var(--attention-7)",
        "--ring-danger": "var(--danger-7)",
        "--separator-neutral": "var(--neutral-6)",
        "--separator-accent": "var(--accent-6)",
        "--separator-success": "var(--success-6)",
        "--separator-attention": "var(--attention-6)",
        "--separator-danger": "var(--danger-6)",
        "--component-background-neutral-default": "var(--neutral-3)",
        "--component-background-neutral-hover": "var(--neutral-4)",
        "--component-background-neutral-pressed": "var(--neutral-5)",
        "--component-background-neutral-dark": "var(--neutral-6)",
        "--component-background-neutral-solid-default": "var(--neutral-9)",
        "--component-background-neutral-solid-hover": "var(--neutral-10)",
        "--component-background-accent-default": "var(--accent-3)",
        "--component-background-accent-hover": "var(--accent-4)",
        "--component-background-accent-pressed": "var(--accent-5)",
        "--component-background-accent-dark": "var(--accent-6)",
        "--component-background-accent-solid-default": "var(--accent-9)",
        "--component-background-accent-solid-hover": "var(--accent-10)",
        "--component-background-success-default": "var(--success-3)",
        "--component-background-success-hover": "var(--success-4)",
        "--component-background-success-pressed": "var(--success-5)",
        "--component-background-success-dark": "var(--success-6)",
        "--component-background-success-solid-default": "var(--success-9)",
        "--component-background-success-solid-hover": "var(--success-10)",
        "--component-background-attention-default": "var(--attention-3)",
        "--component-background-attention-hover": "var(--attention-4)",
        "--component-background-attention-pressed": "var(--attention-5)",
        "--component-background-attention-dark": "var(--attention-6)",
        "--component-background-attention-solid-default": "var(--attention-9)",
        "--component-background-attention-solid-hover": "var(--attention-10)",
        "--component-background-danger-default": "var(--danger-3)",
        "--component-background-danger-hover": "var(--danger-4)",
        "--component-background-danger-pressed": "var(--danger-5)",
        "--component-background-danger-dark": "var(--danger-6)",
        "--component-background-danger-solid-default": "var(--danger-9)",
        "--component-background-danger-solid-hover": "var(--danger-10)"
      },
      '[data-theme="dark"]': {
        "--neutral-1": "#111113",
        "--neutral-2": "#18191b",
        "--neutral-3": "#212225",
        "--neutral-4": "#272a2d",
        "--neutral-5": "#2e3135",
        "--neutral-6": "#363a3f",
        "--neutral-7": "#43484e",
        "--neutral-8": "#5a6169",
        "--neutral-9": "#696e77",
        "--neutral-10": "#777b84",
        "--neutral-11": "#b0b4ba",
        "--neutral-12": "#edeef0",
        "--accent-1": "#11131f",
        "--accent-2": "#141726",
        "--accent-3": "#182449",
        "--accent-4": "#1d2e62",
        "--accent-5": "#253974",
        "--accent-6": "#304384",
        "--accent-7": "#3a4f97",
        "--accent-8": "#435db1",
        "--accent-9": "#3e63dd",
        "--accent-10": "#5472e4",
        "--accent-11": "#9eb1ff",
        "--accent-12": "#d6e1ff",
        "--success-1": "#0e1512",
        "--success-2": "#121b17",
        "--success-3": "#132d21",
        "--success-4": "#113b29",
        "--success-5": "#174933",
        "--success-6": "#20573e",
        "--success-7": "#28684a",
        "--success-8": "#2f7c57",
        "--success-9": "#30a46c",
        "--success-10": "#33b074",
        "--success-11": "#3dd68c",
        "--success-12": "#b1f1cb",
        "--danger-1": "#191111",
        "--danger-2": "#201314",
        "--danger-3": "#3b1219",
        "--danger-4": "#500f1c",
        "--danger-5": "#611623",
        "--danger-6": "#72232d",
        "--danger-7": "#8c333a",
        "--danger-8": "#b54548",
        "--danger-9": "#e5484d",
        "--danger-10": "#ec5d5e",
        "--danger-11": "#ff9592",
        "--danger-12": "#ffd1d9",
        "--attention-1": "#16120c",
        "--attention-2": "#1d180f",
        "--attention-3": "#302008",
        "--attention-4": "#3f2700",
        "--attention-5": "#4d3000",
        "--attention-6": "#5c3d05",
        "--attention-7": "#714f19",
        "--attention-8": "#8f6424",
        "--attention-9": "#ffc53d",
        "--attention-10": "#ffd60a",
        "--attention-11": "#ffca16",
        "--attention-12": "#ffe7b3",
        "--overlay": "#000000b3",
        "--text-neutral-default": "var(--neutral-12)",
        "--text-neutral-muted": "var(--neutral-11)",
        "--text-accent-default": "var(--accent-12)",
        "--text-accent-muted": "var(--accent-11)",
        "--text-success-default": "var(--success-12)",
        "--text-success-muted": "var(--success-11)",
        "--text-attention-default": "var(--attention-12)",
        "--text-attention-muted": "var(--attention-11)",
        "--text-danger-default": "var(--danger-12)",
        "--text-danger-muted": "var(--danger-11)",
        "--background-neutral-default": "var(--neutral-1)",
        "--background-neutral-muted": "var(--neutral-2)",
        "--background-accent-default": "var(--accent-1)",
        "--background-accent-muted": "var(--accent-2)",
        "--background-success-default": "var(--success-1)",
        "--background-success-muted": "var(--success-2)",
        "--background-attention-default": "var(--attention-1)",
        "--background-attention-muted": "var(--attention-2)",
        "--background-danger-default": "var(--danger-1)",
        "--background-danger-muted": "var(--danger-2)",
        "--border-neutral-muted": "var(--neutral-6)",
        "--border-neutral-default": "var(--neutral-7)",
        "--border-neutral-dark": "var(--neutral-8)",
        "--border-accent-muted": "var(--accent-6)",
        "--border-accent-default": "var(--accent-7)",
        "--border-accent-dark": "var(--accent-8)",
        "--border-success-muted": "var(--success-6)",
        "--border-success-default": "var(--success-7)",
        "--border-success-dark": "var(--success-8)",
        "--border-attention-muted": "var(--attention-6)",
        "--border-attention-default": "var(--attention-7)",
        "--border-attention-dark": "var(--attention-8)",
        "--border-danger-muted": "var(--danger-6)",
        "--border-danger-default": "var(--danger-7)",
        "--border-danger-dark": "var(--danger-8)",
        "--ring-neutral": "var(--neutral-7)",
        "--ring-accent": "var(--accent-7)",
        "--ring-success": "var(--success-7)",
        "--ring-attention": "var(--attention-7)",
        "--ring-danger": "var(--danger-7)",
        "--separator-neutral": "var(--neutral-6)",
        "--separator-accent": "var(--accent-6)",
        "--separator-success": "var(--success-6)",
        "--separator-attention": "var(--attention-6)",
        "--separator-danger": "var(--danger-6)",
        "--component-background-neutral-default": "var(--neutral-3)",
        "--component-background-neutral-hover": "var(--neutral-4)",
        "--component-background-neutral-pressed": "var(--neutral-5)",
        "--component-background-neutral-dark": "var(--neutral-6)",
        "--component-background-neutral-solid-default": "var(--neutral-9)",
        "--component-background-neutral-solid-hover": "var(--neutral-10)",
        "--component-background-accent-default": "var(--accent-3)",
        "--component-background-accent-hover": "var(--accent-4)",
        "--component-background-accent-pressed": "var(--accent-5)",
        "--component-background-accent-dark": "var(--accent-6)",
        "--component-background-accent-solid-default": "var(--accent-9)",
        "--component-background-accent-solid-hover": "var(--accent-10)",
        "--component-background-success-default": "var(--success-3)",
        "--component-background-success-hover": "var(--success-4)",
        "--component-background-success-pressed": "var(--success-5)",
        "--component-background-success-dark": "var(--success-6)",
        "--component-background-success-solid-default": "var(--success-9)",
        "--component-background-success-solid-hover": "var(--success-10)",
        "--component-background-attention-default": "var(--attention-3)",
        "--component-background-attention-hover": "var(--attention-4)",
        "--component-background-attention-pressed": "var(--attention-5)",
        "--component-background-attention-dark": "var(--attention-6)",
        "--component-background-attention-solid-default": "var(--attention-9)",
        "--component-background-attention-solid-hover": "var(--attention-10)",
        "--component-background-danger-default": "var(--danger-3)",
        "--component-background-danger-hover": "var(--danger-4)",
        "--component-background-danger-pressed": "var(--danger-5)",
        "--component-background-danger-dark": "var(--danger-6)",
        "--component-background-danger-solid-default": "var(--danger-9)",
        "--component-background-danger-solid-hover": "var(--danger-10)"
      },
      '[data-filter="deuteranopia"]:where([data-theme="light"])': {
        "--success-1": "#fbfdff",
        "--success-2": "#f4faff",
        "--success-3": "#e6f4fe",
        "--success-4": "#d5efff",
        "--success-5": "#c2e5ff",
        "--success-6": "#acd8fc",
        "--success-7": "#8ec8f6",
        "--success-8": "#5eb1ef",
        "--success-9": "#0090ff",
        "--success-10": "#0588f0",
        "--success-11": "#0d74ce",
        "--success-12": "#113264",
        "--danger-1": "#fefdfc",
        "--danger-2": "#fcf9f6",
        "--danger-3": "#f6eee7",
        "--danger-4": "#f0e4d9",
        "--danger-5": "#ebdaca",
        "--danger-6": "#e4cdb7",
        "--danger-7": "#dcbc9f",
        "--danger-8": "#cea37e",
        "--danger-9": "#ad7f58",
        "--danger-10": "#a07553",
        "--danger-11": "#815e46",
        "--danger-12": "#3e332e",
        "--text-success-default": "var(--success-12)",
        "--text-success-muted": "var(--success-11)",
        "--text-danger-default": "var(--danger-12)",
        "--text-danger-muted": "var(--danger-11)",
        "--background-success-default": "var(--success-1)",
        "--background-success-muted": "var(--success-2)",
        "--background-danger-default": "var(--danger-1)",
        "--background-danger-muted": "var(--danger-2)",
        "--border-success-muted": "var(--success-6)",
        "--border-success-default": "var(--success-7)",
        "--border-success-dark": "var(--success-8)",
        "--border-danger-muted": "var(--danger-6)",
        "--border-danger-default": "var(--danger-7)",
        "--border-danger-dark": "var(--danger-8)",
        "--ring-success": "var(--success-7)",
        "--ring-danger": "var(--danger-7)",
        "--separator-success": "var(--success-6)",
        "--separator-danger": "var(--danger-6)",
        "--component-background-success-default": "var(--success-3)",
        "--component-background-success-hover": "var(--success-4)",
        "--component-background-success-pressed": "var(--success-5)",
        "--component-background-success-dark": "var(--success-6)",
        "--component-background-success-solid-default": "var(--success-9)",
        "--component-background-success-solid-hover": "var(--success-10)",
        "--component-background-danger-default": "var(--danger-3)",
        "--component-background-danger-hover": "var(--danger-4)",
        "--component-background-danger-pressed": "var(--danger-5)",
        "--component-background-danger-dark": "var(--danger-6)",
        "--component-background-danger-solid-default": "var(--danger-9)",
        "--component-background-danger-solid-hover": "var(--danger-10)"
      },
      '[data-filter="deuteranopia"]:where([data-theme="dark"])': {
        "--success-1": "#0d1520",
        "--success-2": "#111927",
        "--success-3": "#0d2847",
        "--success-4": "#003362",
        "--success-5": "#004074",
        "--success-6": "#104d87",
        "--success-7": "#205d9e",
        "--success-8": "#2870bd",
        "--success-9": "#0090ff",
        "--success-10": "#3b9eff",
        "--success-11": "#70b8ff",
        "--success-12": "#c2e6ff",
        "--danger-1": "#12110f",
        "--danger-2": "#1c1816",
        "--danger-3": "#28211d",
        "--danger-4": "#322922",
        "--danger-5": "#3e3128",
        "--danger-6": "#4d3c2f",
        "--danger-7": "#614a39",
        "--danger-8": "#7c5f46",
        "--danger-9": "#ad7f58",
        "--danger-10": "#b88c67",
        "--danger-11": "#dbb594",
        "--danger-12": "#f2e1ca",
        "--text-success-default": "var(--success-12)",
        "--text-success-muted": "var(--success-11)",
        "--text-danger-default": "var(--danger-12)",
        "--text-danger-muted": "var(--danger-11)",
        "--background-success-default": "var(--success-1)",
        "--background-success-muted": "var(--success-2)",
        "--background-danger-default": "var(--danger-1)",
        "--background-danger-muted": "var(--danger-2)",
        "--border-success-muted": "var(--success-6)",
        "--border-success-default": "var(--success-7)",
        "--border-success-dark": "var(--success-8)",
        "--border-danger-muted": "var(--danger-6)",
        "--border-danger-default": "var(--danger-7)",
        "--border-danger-dark": "var(--danger-8)",
        "--ring-success": "var(--success-7)",
        "--ring-danger": "var(--danger-7)",
        "--separator-success": "var(--success-6)",
        "--separator-danger": "var(--danger-6)",
        "--component-background-success-default": "var(--success-3)",
        "--component-background-success-hover": "var(--success-4)",
        "--component-background-success-pressed": "var(--success-5)",
        "--component-background-success-dark": "var(--success-6)",
        "--component-background-success-solid-default": "var(--success-9)",
        "--component-background-success-solid-hover": "var(--success-10)",
        "--component-background-danger-default": "var(--danger-3)",
        "--component-background-danger-hover": "var(--danger-4)",
        "--component-background-danger-pressed": "var(--danger-5)",
        "--component-background-danger-dark": "var(--danger-6)",
        "--component-background-danger-solid-default": "var(--danger-9)",
        "--component-background-danger-solid-hover": "var(--danger-10)"
      },
      '[data-filter="protanopia"]:where([data-theme="light"])': {
        "--success-1": "#fbfdff",
        "--success-2": "#f4faff",
        "--success-3": "#e6f4fe",
        "--success-4": "#d5efff",
        "--success-5": "#c2e5ff",
        "--success-6": "#acd8fc",
        "--success-7": "#8ec8f6",
        "--success-8": "#5eb1ef",
        "--success-9": "#0090ff",
        "--success-10": "#0588f0",
        "--success-11": "#0d74ce",
        "--success-12": "#113264",
        "--danger-1": "#fefdfc",
        "--danger-2": "#fcf9f6",
        "--danger-3": "#f6eee7",
        "--danger-4": "#f0e4d9",
        "--danger-5": "#ebdaca",
        "--danger-6": "#e4cdb7",
        "--danger-7": "#dcbc9f",
        "--danger-8": "#cea37e",
        "--danger-9": "#ad7f58",
        "--danger-10": "#a07553",
        "--danger-11": "#815e46",
        "--danger-12": "#3e332e",
        "--text-success-default": "var(--success-12)",
        "--text-success-muted": "var(--success-11)",
        "--text-danger-default": "var(--danger-12)",
        "--text-danger-muted": "var(--danger-11)",
        "--background-success-default": "var(--success-1)",
        "--background-success-muted": "var(--success-2)",
        "--background-danger-default": "var(--danger-1)",
        "--background-danger-muted": "var(--danger-2)",
        "--border-success-muted": "var(--success-6)",
        "--border-success-default": "var(--success-7)",
        "--border-success-dark": "var(--success-8)",
        "--border-danger-muted": "var(--danger-6)",
        "--border-danger-default": "var(--danger-7)",
        "--border-danger-dark": "var(--danger-8)",
        "--ring-success": "var(--success-7)",
        "--ring-danger": "var(--danger-7)",
        "--separator-success": "var(--success-6)",
        "--separator-danger": "var(--danger-6)",
        "--component-background-success-default": "var(--success-3)",
        "--component-background-success-hover": "var(--success-4)",
        "--component-background-success-pressed": "var(--success-5)",
        "--component-background-success-dark": "var(--success-6)",
        "--component-background-success-solid-default": "var(--success-9)",
        "--component-background-success-solid-hover": "var(--success-10)",
        "--component-background-danger-default": "var(--danger-3)",
        "--component-background-danger-hover": "var(--danger-4)",
        "--component-background-danger-pressed": "var(--danger-5)",
        "--component-background-danger-dark": "var(--danger-6)",
        "--component-background-danger-solid-default": "var(--danger-9)",
        "--component-background-danger-solid-hover": "var(--danger-10)"
      },
      '[data-filter="protanopia"]:where([data-theme="dark"])': {
        "--success-1": "#0d1520",
        "--success-2": "#111927",
        "--success-3": "#0d2847",
        "--success-4": "#003362",
        "--success-5": "#004074",
        "--success-6": "#104d87",
        "--success-7": "#205d9e",
        "--success-8": "#2870bd",
        "--success-9": "#0090ff",
        "--success-10": "#3b9eff",
        "--success-11": "#70b8ff",
        "--success-12": "#c2e6ff",
        "--danger-1": "#12110f",
        "--danger-2": "#1c1816",
        "--danger-3": "#28211d",
        "--danger-4": "#322922",
        "--danger-5": "#3e3128",
        "--danger-6": "#4d3c2f",
        "--danger-7": "#614a39",
        "--danger-8": "#7c5f46",
        "--danger-9": "#ad7f58",
        "--danger-10": "#b88c67",
        "--danger-11": "#dbb594",
        "--danger-12": "#f2e1ca",
        "--text-success-default": "var(--success-12)",
        "--text-success-muted": "var(--success-11)",
        "--text-danger-default": "var(--danger-12)",
        "--text-danger-muted": "var(--danger-11)",
        "--background-success-default": "var(--success-1)",
        "--background-success-muted": "var(--success-2)",
        "--background-danger-default": "var(--danger-1)",
        "--background-danger-muted": "var(--danger-2)",
        "--border-success-muted": "var(--success-6)",
        "--border-success-default": "var(--success-7)",
        "--border-success-dark": "var(--success-8)",
        "--border-danger-muted": "var(--danger-6)",
        "--border-danger-default": "var(--danger-7)",
        "--border-danger-dark": "var(--danger-8)",
        "--ring-success": "var(--success-7)",
        "--ring-danger": "var(--danger-7)",
        "--separator-success": "var(--success-6)",
        "--separator-danger": "var(--danger-6)",
        "--component-background-success-default": "var(--success-3)",
        "--component-background-success-hover": "var(--success-4)",
        "--component-background-success-pressed": "var(--success-5)",
        "--component-background-success-dark": "var(--success-6)",
        "--component-background-success-solid-default": "var(--success-9)",
        "--component-background-success-solid-hover": "var(--success-10)",
        "--component-background-danger-default": "var(--danger-3)",
        "--component-background-danger-hover": "var(--danger-4)",
        "--component-background-danger-pressed": "var(--danger-5)",
        "--component-background-danger-dark": "var(--danger-6)",
        "--component-background-danger-solid-default": "var(--danger-9)",
        "--component-background-danger-solid-hover": "var(--danger-10)"
      },
      '[data-filter="tritanopia"]:where([data-theme="light"])': {
        "--danger-1": "#fffcfc",
        "--danger-2": "#fff8f7",
        "--danger-3": "#feebe7",
        "--danger-4": "#ffdcd3",
        "--danger-5": "#ffcdc2",
        "--danger-6": "#fdbdaf",
        "--danger-7": "#f5a898",
        "--danger-8": "#ec8e7b",
        "--danger-9": "#e54d2e",
        "--danger-10": "#dd4425",
        "--danger-11": "#d13415",
        "--danger-12": "#5c271f",
        "--success-1": "#fbfefb",
        "--success-2": "#f5fbf5",
        "--success-3": "#e9f6e9",
        "--success-4": "#daf1db",
        "--success-5": "#c9e8ca",
        "--success-6": "#b2ddb5",
        "--success-7": "#94ce9a",
        "--success-8": "#65ba74",
        "--success-9": "#46a758",
        "--success-10": "#3e9b4f",
        "--success-11": "#2a7e3b",
        "--success-12": "#203c25",
        "--accent-1": "#fbfefd",
        "--accent-2": "#f4fbf7",
        "--accent-3": "#e6f7ed",
        "--accent-4": "#d6f1e3",
        "--accent-5": "#c3e9d7",
        "--accent-6": "#acdec8",
        "--accent-7": "#8bceb6",
        "--accent-8": "#56ba9f",
        "--accent-9": "#29a383",
        "--accent-10": "#26997b",
        "--accent-11": "#208368",
        "--accent-12": "#1d3b31",
        "--text-accent-default": "var(--accent-12)",
        "--text-accent-muted": "var(--accent-11)",
        "--text-success-default": "var(--success-12)",
        "--text-success-muted": "var(--success-11)",
        "--text-danger-default": "var(--danger-12)",
        "--text-danger-muted": "var(--danger-11)",
        "--background-accent-default": "var(--accent-1)",
        "--background-accent-muted": "var(--accent-2)",
        "--background-success-default": "var(--success-1)",
        "--background-success-muted": "var(--success-2)",
        "--background-danger-default": "var(--danger-1)",
        "--background-danger-muted": "var(--danger-2)",
        "--border-accent-muted": "var(--accent-6)",
        "--border-accent-default": "var(--accent-7)",
        "--border-accent-dark": "var(--accent-8)",
        "--border-success-muted": "var(--success-6)",
        "--border-success-default": "var(--success-7)",
        "--border-success-dark": "var(--success-8)",
        "--border-danger-muted": "var(--danger-6)",
        "--border-danger-default": "var(--danger-7)",
        "--border-danger-dark": "var(--danger-8)",
        "--ring-accent": "var(--accent-7)",
        "--ring-success": "var(--success-7)",
        "--ring-danger": "var(--danger-7)",
        "--separator-accent": "var(--accent-6)",
        "--separator-success": "var(--success-6)",
        "--separator-danger": "var(--danger-6)",
        "--component-background-accent-default": "var(--accent-3)",
        "--component-background-accent-hover": "var(--accent-4)",
        "--component-background-accent-pressed": "var(--accent-5)",
        "--component-background-accent-dark": "var(--accent-6)",
        "--component-background-accent-solid-default": "var(--accent-9)",
        "--component-background-accent-solid-hover": "var(--accent-10)",
        "--component-background-success-default": "var(--success-3)",
        "--component-background-success-hover": "var(--success-4)",
        "--component-background-success-pressed": "var(--success-5)",
        "--component-background-success-dark": "var(--success-6)",
        "--component-background-success-solid-default": "var(--success-9)",
        "--component-background-success-solid-hover": "var(--success-10)",
        "--component-background-danger-default": "var(--danger-3)",
        "--component-background-danger-hover": "var(--danger-4)",
        "--component-background-danger-pressed": "var(--danger-5)",
        "--component-background-danger-dark": "var(--danger-6)",
        "--component-background-danger-solid-default": "var(--danger-9)",
        "--component-background-danger-solid-hover": "var(--danger-10)"
      },
      '[data-filter="tritanopia"]:where([data-theme="dark"])': {
        "--accent-1": "#0d1512",
        "--accent-2": "#121c18",
        "--accent-3": "#0f2e22",
        "--accent-4": "#0b3b2c",
        "--accent-5": "#114837",
        "--accent-6": "#1b5745",
        "--accent-7": "#246854",
        "--accent-8": "#2a7e68",
        "--accent-9": "#29a383",
        "--accent-10": "#27b08b",
        "--accent-11": "#1fd8a4",
        "--accent-12": "#adf0d4",
        "--success-1": "#0e1511",
        "--success-2": "#141a15",
        "--success-3": "#1b2a1e",
        "--success-4": "#1d3a24",
        "--success-5": "#25482d",
        "--success-6": "#2d5736",
        "--success-7": "#366740",
        "--success-8": "#3e7949",
        "--success-9": "#46a758",
        "--success-10": "#53b365",
        "--success-11": "#71d083",
        "--success-12": "#c2f0c2",
        "--danger-1": "#181111",
        "--danger-2": "#1f1513",
        "--danger-3": "#391714",
        "--danger-4": "#4e1511",
        "--danger-5": "#5e1c16",
        "--danger-6": "#6e2920",
        "--danger-7": "#853a2d",
        "--danger-8": "#ac4d39",
        "--danger-9": "#e54d2e",
        "--danger-10": "#ec6142",
        "--danger-11": "#ff977d",
        "--danger-12": "#fbd3cb",
        "--text-accent-default": "var(--accent-12)",
        "--text-accent-muted": "var(--accent-11)",
        "--text-success-default": "var(--success-12)",
        "--text-success-muted": "var(--success-11)",
        "--text-danger-default": "var(--danger-12)",
        "--text-danger-muted": "var(--danger-11)",
        "--background-accent-default": "var(--accent-1)",
        "--background-accent-muted": "var(--accent-2)",
        "--background-success-default": "var(--success-1)",
        "--background-success-muted": "var(--success-2)",
        "--background-danger-default": "var(--danger-1)",
        "--background-danger-muted": "var(--danger-2)",
        "--border-accent-muted": "var(--accent-6)",
        "--border-accent-default": "var(--accent-7)",
        "--border-accent-dark": "var(--accent-8)",
        "--border-success-muted": "var(--success-6)",
        "--border-success-default": "var(--success-7)",
        "--border-success-dark": "var(--success-8)",
        "--border-danger-muted": "var(--danger-6)",
        "--border-danger-default": "var(--danger-7)",
        "--border-danger-dark": "var(--danger-8)",
        "--ring-accent": "var(--accent-7)",
        "--ring-success": "var(--success-7)",
        "--ring-danger": "var(--danger-7)",
        "--separator-accent": "var(--accent-6)",
        "--separator-success": "var(--success-6)",
        "--separator-danger": "var(--danger-6)",
        "--component-background-accent-default": "var(--accent-3)",
        "--component-background-accent-hover": "var(--accent-4)",
        "--component-background-accent-pressed": "var(--accent-5)",
        "--component-background-accent-dark": "var(--accent-6)",
        "--component-background-accent-solid-default": "var(--accent-9)",
        "--component-background-accent-solid-hover": "var(--accent-10)",
        "--component-background-success-default": "var(--success-3)",
        "--component-background-success-hover": "var(--success-4)",
        "--component-background-success-pressed": "var(--success-5)",
        "--component-background-success-dark": "var(--success-6)",
        "--component-background-success-solid-default": "var(--success-9)",
        "--component-background-success-solid-hover": "var(--success-10)",
        "--component-background-danger-default": "var(--danger-3)",
        "--component-background-danger-hover": "var(--danger-4)",
        "--component-background-danger-pressed": "var(--danger-5)",
        "--component-background-danger-dark": "var(--danger-6)",
        "--component-background-danger-solid-default": "var(--danger-9)",
        "--component-background-danger-solid-hover": "var(--danger-10)"
      }
    });

    addUtilities({
      ".focus-ring-neutral": {
        "@apply focus:outline-none focus:ring-2 focus:ring-neutral focus:ring-offset-0":
          {}
      },
      ".focus-ring-accent": {
        "@apply focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-0":
          {}
      },
      ".focus-ring-success": {
        "@apply focus:outline-none focus:ring-2 focus:ring-success focus:ring-offset-0":
          {}
      },
      ".focus-ring-attention": {
        "@apply focus:outline-none focus:ring-2 focus:ring-attention focus:ring-offset-0":
          {}
      },
      ".focus-ring-danger": {
        "@apply focus:outline-none focus:ring-2 focus:ring-danger focus:ring-offset-0":
          {}
      },
      ":where([data-font-size='large'],[data-dyslexia-mode='enabled'],[data-reduced-motion='enabled'],[data-spacing='comfortable'],[data-high-contrast='enabled'],[data-cursor='bigger'],[data-links='underlined'],[data-filter='deuteranopia'],[data-filter='protanopia'],[data-filter='tritanopia'])":
        {
          ".focus-ring-neutral": {
            "@apply focus:outline-none focus:ring-4 focus:ring-neutral focus:ring-offset-2 focus:ring-offset-neutral":
              {}
          },
          ".focus-ring-accent": {
            "@apply focus:outline-none focus:ring-4 focus:ring-accent focus:ring-offset-2 focus:ring-offset-neutral":
              {}
          },
          ".focus-ring-success": {
            "@apply focus:outline-none focus:ring-4 focus:ring-success focus:ring-offset-2 focus:ring-offset-neutral":
              {}
          },
          ".focus-ring-attention": {
            "@apply focus:outline-none focus:ring-4 focus:ring-attention focus:ring-offset-2 focus:ring-offset-neutral":
              {}
          },
          ".focus-ring-danger": {
            "@apply focus:outline-none focus:ring-4 focus:ring-danger focus:ring-offset-2 focus:ring-offset-neutral":
              {}
          }
        }
    });
  },
  {
    theme: {
      extend: {
        colors: {
          neutral: {
            1: "var(--neutral-1)",
            2: "var(--neutral-2)",
            3: "var(--neutral-3)",
            4: "var(--neutral-4)",
            5: "var(--neutral-5)",
            6: "var(--neutral-6)",
            7: "var(--neutral-7)",
            8: "var(--neutral-8)",
            9: "var(--neutral-9)",
            10: "var(--neutral-10)",
            11: "var(--neutral-11)",
            12: "var(--neutral-12)"
          },
          accent: {
            1: "var(--accent-1)",
            2: "var(--accent-2)",
            3: "var(--accent-3)",
            4: "var(--accent-4)",
            5: "var(--accent-5)",
            6: "var(--accent-6)",
            7: "var(--accent-7)",
            8: "var(--accent-8)",
            9: "var(--accent-9)",
            10: "var(--accent-10)",
            11: "var(--accent-11)",
            12: "var(--accent-12)"
          },
          success: {
            1: "var(--success-1)",
            2: "var(--success-2)",
            3: "var(--success-3)",
            4: "var(--success-4)",
            5: "var(--success-5)",
            6: "var(--success-6)",
            7: "var(--success-7)",
            8: "var(--success-8)",
            9: "var(--success-9)",
            10: "var(--success-10)",
            11: "var(--success-11)",
            12: "var(--success-12)"
          },
          attention: {
            1: "var(--attention-1)",
            2: "var(--attention-2)",
            3: "var(--attention-3)",
            4: "var(--attention-4)",
            5: "var(--attention-5)",
            6: "var(--attention-6)",
            7: "var(--attention-7)",
            8: "var(--attention-8)",
            9: "var(--attention-9)",
            10: "var(--attention-10)",
            11: "var(--attention-11)",
            12: "var(--attention-12)"
          },
          danger: {
            1: "var(--danger-1)",
            2: "var(--danger-2)",
            3: "var(--danger-3)",
            4: "var(--danger-4)",
            5: "var(--danger-5)",
            6: "var(--danger-6)",
            7: "var(--danger-7)",
            8: "var(--danger-8)",
            9: "var(--danger-9)",
            10: "var(--danger-10)",
            11: "var(--danger-11)",
            12: "var(--danger-12)"
          },
          overlay: "hsla(var(--overlay)",
          separator: {
            neutral: "var(--separator-neutral)",
            accent: "var(--separator-accent)",
            success: "var(--separator-success)",
            attention: "var(--separator-attention)",
            danger: "var(--separator-danger)"
          }
        },
        textColor: {
          neutral: {
            default: "var(--text-neutral-default)",
            muted: "var(--text-neutral-muted)"
          },
          accent: {
            default: "var(--text-accent-default)",
            muted: "var(--text-accent-muted)"
          },
          success: {
            default: "var(--text-success-default)",
            muted: "var(--text-success-muted)"
          },
          attention: {
            default: "var(--text-attention-default)",
            muted: "var(--text-attention-muted)"
          },
          danger: {
            default: "var(--text-danger-default)",
            muted: "var(--text-danger-muted)"
          }
        },
        backgroundColor: {
          neutral: {
            default: "var(--background-neutral-default)",
            muted: "var(--background-neutral-muted)"
          },
          accent: {
            default: "var(--background-accent-default)",
            muted: "var(--background-accent-muted)"
          },
          success: {
            default: "var(--background-success-default)",
            muted: "var(--background-success-muted)"
          },
          attention: {
            default: "var(--background-attention-default)",
            muted: "var(--background-attention-muted)"
          },
          danger: {
            default: "var(--background-danger-default)",
            muted: "var(--background-danger-muted)"
          },
          component: {
            neutral: {
              default: "var(--component-background-neutral-default)",
              hover: "var(--component-background-neutral-hover)",
              pressed: "var(--component-background-neutral-pressed)",
              dark: "var(--component-background-neutral-dark)",
              solid: {
                default: "var(--component-background-neutral-solid-default)",
                hover: "var(--component-background-neutral-solid-hover)"
              }
            },
            accent: {
              default: "var(--component-background-accent-default)",
              hover: "var(--component-background-accent-hover)",
              pressed: "var(--component-background-accent-pressed)",
              dark: "var(--component-background-accent-dark)",
              solid: {
                default: "var(--component-background-accent-solid-default)",
                hover: "var(--component-background-accent-solid-hover)"
              }
            },
            success: {
              default: "var(--component-background-success-default)",
              hover: "var(--component-background-success-hover)",
              pressed: "var(--component-background-success-pressed)",
              dark: "var(--component-background-success-dark)",
              solid: {
                default: "var(--component-background-success-solid-default)",
                hover: "var(--component-background-success-solid-hover)"
              }
            },
            attention: {
              default: "var(--component-background-attention-default)",
              hover: "var(--component-background-attention-hover)",
              pressed: "var(--component-background-attention-pressed)",
              dark: "var(--component-background-attention-dark)",
              solid: {
                default: "var(--component-background-attention-solid-default)",
                hover: "var(--component-background-attention-solid-hover)"
              }
            },
            danger: {
              default: "var(--component-background-danger-default)",
              hover: "var(--component-background-danger-hover)",
              pressed: "var(--component-background-danger-pressed)",
              dark: "var(--component-background-danger-dark)",
              solid: {
                default: "var(--component-background-danger-solid-default)",
                hover: "var(--component-background-danger-solid-hover)"
              }
            }
          }
        },
        borderColor: {
          neutral: {
            muted: "var(--border-neutral-muted)",
            default: "var(--border-neutral-default)",
            dark: "var(--border-neutral-dark)"
          },
          accent: {
            muted: "var(--border-accent-muted)",
            default: "var(--border-accent-default)",
            dark: "var(--border-accent-dark)"
          },
          success: {
            muted: "var(--border-success-muted)",
            default: "var(--border-success-default)",
            dark: "var(--border-success-dark)"
          },
          attention: {
            muted: "var(--border-attention-muted)",
            default: "var(--border-attention-default)",
            dark: "var(--border-attention-dark)"
          },
          danger: {
            muted: "var(--border-danger-muted)",
            default: "var(--border-danger-default)",
            dark: "var(--border-danger-dark)"
          }
        },
        ringColor: {
          neutral: "var(--ring-neutral)",
          accent: "var(--ring-accent)",
          success: "var(--ring-success)",
          attention: "var(--ring-attention)",
          danger: "var(--ring-danger)"
        },
        ringOffsetColor: {
          neutral: "var(--neutral-1)"
        }
      }
    }
  }
);
